<?php
/**
 * Shared helpers: meta keys, statuses, document types, sanitization, formatting.
 *
 * Everything that both the admin side and the frontend need lives here so the
 * meta box code and the shortcode code never drift apart.
 *
 * @package BoardMeetingDocuments
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class BMD_Helpers
 */
class BMD_Helpers {

	/**
	 * Meta keys. Kept as separate, human-readable keys so data can be migrated
	 * in and out with plain WP functions (update_post_meta / get_post_meta).
	 */
	const META_DATE       = '_bmd_meeting_date';      // string  YYYY-MM-DD
	const META_STATUS     = '_bmd_meeting_status';    // string  normal|cancelled|special|joint
	const META_AGENDA     = '_bmd_agenda_documents';  // array   [ [ 'attachment_id' => int, 'label' => string ], ... ]
	const META_MINUTES    = '_bmd_minutes_documents'; // array   same structure as agenda
	const META_AUTO_TITLE = '_bmd_auto_title';        // int     1 when the post title was auto-generated by the plugin

	/**
	 * Returns the meeting statuses (value => label).
	 *
	 * @return array<string,string>
	 */
	public static function get_statuses(): array {
		return array(
			'normal'    => __( 'Normal', 'board-meeting-documents' ),
			'cancelled' => __( 'Cancelled', 'board-meeting-documents' ),
			'special'   => __( 'Special Meeting', 'board-meeting-documents' ),
			'joint'     => __( 'Joint Meeting', 'board-meeting-documents' ),
		);
	}

	/**
	 * Returns the text appended to a frontend title for a given status.
	 * "Normal" deliberately produces no suffix.
	 *
	 * @param string $status Status key.
	 * @return string
	 */
	public static function get_status_suffix( string $status ): string {
		$suffixes = array(
			'normal'    => '',
			'cancelled' => __( 'Meeting Cancelled', 'board-meeting-documents' ),
			'special'   => __( 'Special Meeting', 'board-meeting-documents' ),
			'joint'     => __( 'Joint Meeting', 'board-meeting-documents' ),
		);

		/**
		 * Filters the status suffixes appended to frontend titles.
		 *
		 * @param array<string,string> $suffixes Status key => suffix text.
		 */
		$suffixes = apply_filters( 'bmd_status_suffixes', $suffixes );

		return isset( $suffixes[ $status ] ) ? (string) $suffixes[ $status ] : '';
	}

	/**
	 * Returns the configuration for each document type (agenda, minutes).
	 *
	 * Adding a third document type later only requires adding an entry here.
	 *
	 * @return array<string,array<string,string>>
	 */
	public static function get_document_types(): array {
		return array(
			'agenda'  => array(
				'meta_key'      => self::META_AGENDA,
				'field_name'    => 'bmd_agenda_documents',
				'section_title' => __( 'Agenda Documents', 'board-meeting-documents' ),
				'add_button'    => __( 'Add Agenda Document', 'board-meeting-documents' ),
				'default_label' => __( 'Agenda', 'board-meeting-documents' ),
				'title_prefix'  => __( 'Agenda', 'board-meeting-documents' ),
				'empty_admin'   => __( 'No agenda documents added yet.', 'board-meeting-documents' ),
				'empty_front'   => __( 'No agendas are available at this time.', 'board-meeting-documents' ),
			),
			'minutes' => array(
				'meta_key'      => self::META_MINUTES,
				'field_name'    => 'bmd_minutes_documents',
				'section_title' => __( 'Minutes Documents', 'board-meeting-documents' ),
				'add_button'    => __( 'Add Minutes Document', 'board-meeting-documents' ),
				'default_label' => __( 'Minutes', 'board-meeting-documents' ),
				'title_prefix'  => __( 'Minutes', 'board-meeting-documents' ),
				'empty_admin'   => __( 'No minutes documents added yet.', 'board-meeting-documents' ),
				'empty_front'   => __( 'No minutes are available at this time.', 'board-meeting-documents' ),
			),
		);
	}

	/**
	 * Validates a YYYY-MM-DD date string. Returns '' when invalid.
	 *
	 * @param string $value Raw value.
	 * @return string
	 */
	public static function sanitize_date( string $value ): string {
		$value = trim( $value );

		if ( ! preg_match( '/^(\d{4})-(\d{2})-(\d{2})$/', $value, $m ) ) {
			return '';
		}

		if ( ! checkdate( (int) $m[2], (int) $m[3], (int) $m[1] ) ) {
			return '';
		}

		return $value;
	}

	/**
	 * Ensures a status key is one we know about; falls back to "normal".
	 *
	 * @param string $value Raw value.
	 * @return string
	 */
	public static function sanitize_status( string $value ): string {
		$value = sanitize_key( $value );
		return array_key_exists( $value, self::get_statuses() ) ? $value : 'normal';
	}

	/**
	 * Formats a YYYY-MM-DD string for display, e.g. "September 23, 2026".
	 *
	 * The date is treated as a calendar date in the site's timezone so it can
	 * never shift by a day because of UTC offsets.
	 *
	 * @param string $ymd Date in YYYY-MM-DD format.
	 * @return string
	 */
	public static function format_date( string $ymd ): string {
		/**
		 * Filters the PHP date format used to display meeting dates.
		 *
		 * @param string $format Default 'F j, Y' (September 23, 2026).
		 */
		$format = apply_filters( 'bmd_date_format', 'F j, Y' );

		$dt = DateTimeImmutable::createFromFormat( '!Y-m-d', $ymd, wp_timezone() );
		if ( ! $dt ) {
			return $ymd;
		}

		return wp_date( $format, $dt->getTimestamp(), wp_timezone() );
	}

	/**
	 * Returns the two parts of the date badge: [ '23', 'Sep' ] (month localized).
	 *
	 * @param string $ymd Date in YYYY-MM-DD format.
	 * @return array{0:string,1:string}
	 */
	public static function format_date_parts( string $ymd ): array {
		$dt = DateTimeImmutable::createFromFormat( '!Y-m-d', $ymd, wp_timezone() );
		if ( ! $dt ) {
			return array( substr( $ymd, 8, 2 ), substr( $ymd, 5, 2 ) );
		}

		$ts = $dt->getTimestamp();

		return array(
			wp_date( 'd', $ts, wp_timezone() ),
			wp_date( 'M', $ts, wp_timezone() ),
		);
	}

	/**
	 * Builds the frontend title, e.g. "Agenda - July 22, 2026 - Meeting Cancelled".
	 *
	 * @param string $type   Document type key (agenda|minutes).
	 * @param string $ymd    Meeting date YYYY-MM-DD.
	 * @param string $status Status key.
	 * @return string
	 */
	public static function get_meeting_title( string $type, string $ymd, string $status ): string {
		$types  = self::get_document_types();
		$prefix = isset( $types[ $type ] ) ? $types[ $type ]['title_prefix'] : ucfirst( $type );

		$title  = $prefix . ' - ' . self::format_date( $ymd );
		$suffix = self::get_status_suffix( $status );

		if ( '' !== $suffix ) {
			$title .= ' - ' . $suffix;
		}

		/**
		 * Filters the meeting title shown on the frontend.
		 *
		 * @param string $title  Generated title.
		 * @param string $type   Document type.
		 * @param string $ymd    Meeting date.
		 * @param string $status Status key.
		 */
		return (string) apply_filters( 'bmd_meeting_title', $title, $type, $ymd, $status );
	}

	/**
	 * Builds the fallback post title used in the admin list when the editor
	 * leaves the title blank, e.g. "Board Meeting - September 23, 2026".
	 *
	 * @param string $ymd    Meeting date YYYY-MM-DD.
	 * @param string $status Status key.
	 * @return string
	 */
	public static function get_auto_title( string $ymd, string $status ): string {
		$title  = __( 'Board Meeting', 'board-meeting-documents' ) . ' - ' . self::format_date( $ymd );
		$suffix = self::get_status_suffix( $status );

		if ( '' !== $suffix ) {
			$title .= ' - ' . $suffix;
		}

		return $title;
	}

	/**
	 * Checks that an attachment exists and is a PDF.
	 *
	 * @param int $attachment_id Attachment post ID.
	 * @return bool
	 */
	public static function is_pdf_attachment( int $attachment_id ): bool {
		if ( $attachment_id <= 0 ) {
			return false;
		}

		$attachment = get_post( $attachment_id );
		if ( ! $attachment || 'attachment' !== $attachment->post_type ) {
			return false;
		}

		return 'application/pdf' === get_post_mime_type( $attachment );
	}

	/**
	 * Sanitizes a raw (already unslashed) documents array coming from $_POST or
	 * from a migration script.
	 *
	 * Output is a clean, zero-indexed list of:
	 *   [ 'attachment_id' => int, 'label' => string ]
	 *
	 * Rows without a valid PDF attachment are dropped. Duplicate attachment IDs
	 * are removed (the same Media Library file is never listed twice).
	 *
	 * @param mixed $raw Raw input.
	 * @return array<int,array{attachment_id:int,label:string}>
	 */
	public static function sanitize_documents( $raw ): array {
		$clean = array();
		$seen  = array();

		if ( ! is_array( $raw ) ) {
			return $clean;
		}

		foreach ( $raw as $row ) {
			if ( ! is_array( $row ) ) {
				continue;
			}

			$attachment_id = isset( $row['attachment_id'] ) ? absint( $row['attachment_id'] ) : 0;
			$label         = isset( $row['label'] ) ? sanitize_text_field( (string) $row['label'] ) : '';

			if ( ! $attachment_id || isset( $seen[ $attachment_id ] ) ) {
				continue;
			}

			if ( ! self::is_pdf_attachment( $attachment_id ) ) {
				continue;
			}

			$seen[ $attachment_id ] = true;

			$clean[] = array(
				'attachment_id' => $attachment_id,
				'label'         => $label,
			);
		}

		return $clean;
	}

	/**
	 * Reads the stored documents for a meeting and normalizes the structure.
	 * Does NOT hit the database for each attachment; that is done in bulk by
	 * the shortcode renderer.
	 *
	 * @param int    $post_id Meeting post ID.
	 * @param string $type    Document type key (agenda|minutes).
	 * @return array<int,array{attachment_id:int,label:string}>
	 */
	public static function get_documents( int $post_id, string $type ): array {
		$types = self::get_document_types();
		if ( ! isset( $types[ $type ] ) ) {
			return array();
		}

		$stored = get_post_meta( $post_id, $types[ $type ]['meta_key'], true );
		if ( ! is_array( $stored ) ) {
			return array();
		}

		$docs = array();
		foreach ( $stored as $row ) {
			if ( ! is_array( $row ) || empty( $row['attachment_id'] ) ) {
				continue;
			}
			$docs[] = array(
				'attachment_id' => absint( $row['attachment_id'] ),
				'label'         => isset( $row['label'] ) ? (string) $row['label'] : '',
			);
		}

		return $docs;
	}

	/**
	 * Returns the meeting date meta (YYYY-MM-DD) or '' when missing/invalid.
	 *
	 * @param int $post_id Meeting post ID.
	 * @return string
	 */
	public static function get_meeting_date( int $post_id ): string {
		return self::sanitize_date( (string) get_post_meta( $post_id, self::META_DATE, true ) );
	}

	/**
	 * Returns the meeting status meta, defaulting to "normal".
	 *
	 * @param int $post_id Meeting post ID.
	 * @return string
	 */
	public static function get_meeting_status( int $post_id ): string {
		return self::sanitize_status( (string) get_post_meta( $post_id, self::META_STATUS, true ) );
	}
}
